# Generated by Django 4.2.30 on 2026-04-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('LOP', 'Loss of Pay')], default='Normal', max_length=10),
        ),
    ]
